
[global]
maintenance_mode = false
telegram_bot_token = { env = "TELEGRAM_BOT_TOKEN" }

[models]
# openai_api_key = { env = "OPENAI_API_KEY" }
# ollama_api_url = { env = "OLLAMA_API_URL" }

[database]
provider = "sqlite"
path = "database.db"

# Uncomment and configure the database you want to use
# [database]
# type = "mongodb"
# host = "localhost"
# port = 27017
# username = { env = "MONGODB_USERNAME" }
# password = { env = "MONGODB_PASSWORD" }
# database_name = "mongodb"

# [database]
# type = "postgres"
# host = "localhost"
# port = 5432
# username = { env = "POSTGRES_USERNAME" }
# password = { env = "POSTGRES_PASSWORD" }
# database_name = "postgres"

# [database]
# type = "mysql"
# host = "localhost"
# port = 3306
# username = { env = "MYSQL_USERNAME" }
# password = { env = "MYSQL_PASSWORD" }
# database_name = "mysql"

[access]
default_user_level = 0
minimum_required_level = 0
